### ISSUE TITLE
Restore --hold argument for upgrade terminal

### ISSUE THREAD

**Issue by fancytenseletters** [I-Dream-in-Code/kde-arch-update-plasmoid#10]
Commit https://github.com/I-Dream-in-Code/kde-arch-update-plasmoid/commit/68df535d7071ba25aa9319b807ff7bb066b1ec4b removed `--hold` argument for Konsole which means it's instantly closed after upgrade.

I think it's valuable for user to investigate upgrade info as it can contain useful info about new config files (pacnew,pacsave) or new optional dependencies. I often keep konsole window in background and look after it when upgrade completed to see if there is anything interesting. Anyway when users choose "show upgrade on konsole" option they probably want to have a chance to see it's complete output.

Other than revert above commit we can make another checkbox option  or someway trap terminal window (i.e. clicking enter closes it) similar like [octopi](https://github.com/aarnt/octopi) do.

**Comment by I-Dream-in-Code** [comment]
Thank you for the feedback.

The reason I removed it was because if you forget to close it and it refreshes in whatever interval you set the entire plasmashell freezes with the mutex locks.

But I added it back and both master and AUR package are updated

**Comment by fancytenseletters** [comment]
Thanks. As for freezing, maybe it should block refresh when terminal is active?

**Comment by I-Dream-in-Code** [comment]
Yeah I can probably just check if mutex is lock is false and just return the function so it doesn't run

**Comment by I-Dream-in-Code** [comment]
@fancytenseletters  i added a simple bool check if when the upgrade process is running to prevent checkupdates from running until the upgrade is ending both konsole and in background

master and AUR are both updated
