### ISSUE TITLE
root privileges

### ISSUE THREAD

**Issue by naraesk** [I-Dream-in-Code/kde-arch-update-plasmoid#11]
Hello,

nice piece of software! I installed the aur package. But when I click "Update System" to update aur packages I recieve an error message, saying I need rooth privileges.

`Fehler: Sie benötigen Root-Rechte, um diese Operation auszuführen.
aura >>= Bitte überprüfen Sie Ihre Eingabe.`

How to fix this? Can this step be integrated into the aur package?

**Comment by I-Dream-in-Code** [comment]
What aur helper are you using?

I'm unclear on if you're trying to install my package or others?

Please give me steps to reproduce

**Comment by I-Dream-in-Code** [comment]
Also please post error message in English if possible

**Comment by naraesk** [comment]
Sorry, thought that's clear. I'm using your program. It shows that one aur-package can be updated. When clicking on the "update system" button a concole window appears with the quoted error message printed.

The message says nothing more than root privileges are required. I have aura installed.

**Comment by I-Dream-in-Code** [comment]
fixed.  I just needed to add sudo to aur.

My apologies for not testing out each command

Master and AUR package are both updated
