### ISSUE TITLE
aura: No aur support

### ISSUE THREAD

**Issue by naraesk** [I-Dream-in-Code/kde-arch-update-plasmoid#12]
Just another small problem using aura as aur-helper:

The command to update aur packages is `aura -Ayu`. But it seems as `aura -Syu` is run by kde-arch-update-plasmoid, which does the same as `pacman -Syu`. With aura it is not possible to update the official repositories and aur at the same time (afaik).

Is this solvable? Or which aur-helper do you recommend?

**Comment by I-Dream-in-Code** [comment]
I just added a fix.

You need to close the konsole window once aura is finished so pacman can run.

Trizen or pacaur do it all in one but pacaur is unmaintained.

both aur package and master are updated
