### ISSUE TITLE
pacaur opens PKGBUILD when upgrading AUR

### ISSUE THREAD

**Issue by nomis6432** [I-Dream-in-Code/kde-arch-update-plasmoid#13]
Currently pacaur opens the PKGBUILD file when updating a package from the AUR. Which can be annoying since he updates the AUR after the arch repositories and therefore pauses the update. I believe this can be fixed by adding --noedit .

**Comment by fancytenseletters** [comment]
Pacaur by default shows only diff between current and last PKGBUILD. You can disable it in pacaur config if don't want this, uncomment and change:
`displaybuildfiles=diff` to `displaybuildfiles=none` in `~/.config/pacaur/config`

**Comment by I-Dream-in-Code** [comment]
fixed thanks for the tip on --noedit

master and aur package are updated

**Comment by fancytenseletters** [comment]
@I-Dream-in-Code  I think this change is a mistake. I showed you how to change  it in pacaur config for every user who's interested. `--noedit` argument in non override-able.

**Comment by nomis6432** [comment]
@fancytenseletters It looks like `--noedit` is only used when `--noconfirm` is enabled. If you want to check the PKGBUILD you can still do so by disabling `--noconfirm`. This makes sense imo since when you use `--noconfirm` you expect the update to run without any interruptions.

**Comment by I-Dream-in-Code** [comment]
@nomis6432 is correct.  `--noedit` is only run when `--noconfirm aur` in settings is enabled.

He/She articulated it perfectly

**Comment by fancytenseletters** [comment]
Ok then. Thx for info.
