### ISSUE TITLE
No exit code on successful update

### ISSUE THREAD

**Issue by Faenriis** [I-Dream-in-Code/kde-arch-update-plasmoid#15]
Current update command can produce output similar to this (ime, mostly when dealing with AUR upgrades):
https://i.imgur.com/HKWa8Vg.png
I am not sure if it's just a behaviour of pacaur, but in any case it would be much safer if the command would end with something like "Update finished - press Enter to exit" instead of having to guess if the command is actually finished and if it's safe to close Konsole window.
Something like what arch updater for gnome shell does.
`konsole -e 'sh -c "pacaur -Syu ; echo Upadate finished - press Enter to exit; read" '`
Thank you.

**Comment by I-Dream-in-Code** [comment]
I'm out of town and away from my computer I'll get to it when I get back

**Comment by I-Dream-in-Code** [comment]
added it however I couldn't add `press enter to exit ; read` because I use the `--hold` argument for konsole so you just need to close the window

AUR and master are both updated

**Comment by Faenriis** [comment]
Thank you, manual window closing is not a big deal, but confirmation of succesful completion of the update is a great to see.

**Comment by I-Dream-in-Code** [comment]
Yeah I added a blank new line and a padded --- above update finished so it's more obvious and not blended in
