### ISSUE TITLE
Pacaur always runs with --noconfirm --noedit options

### ISSUE THREAD

**Issue by fancytenseletters** [I-Dream-in-Code/kde-arch-update-plasmoid#19]
Enabling AUR support always results with `--noconfirm --noedit` options used even when `--noconfirm aur` option is disabled in settings. I tested it with `pacaur`.

**Comment by I-Dream-in-Code** [comment]
You are correct. Thank you for pointing that out.

I modified the backend call to run a string but didn't remove `--noconfirm` and `--noedit` from it properly

commit 3b298087 fixes it

master and AUR are updated
