### ISSUE TITLE
The icon doesn't match the Breeze theme

### ISSUE THREAD

**Issue by NerosTie** [I-Dream-in-Code/kde-arch-update-plasmoid#20]
I think the default icon is too "Arch" and it should more like this one for example:

![screenshot_20180224_104452](https://user-images.githubusercontent.com/4572452/36628958-bf78c91a-194f-11e8-907b-a0e187cf3cbb.png)

**Comment by fancytenseletters** [comment]
Well, Arch is definitely  the target distro here. The above icon is already used by [Discover](https://userbase.kde.org/Discover) so reusing it isn't advisable.  If other Arch-like distros want to package this, the can use the icon of their choice.

**Comment by NerosTie** [comment]
Yes but the actual icon doesn't look like an update icon and it's doesn't match well with the Breeze theme. I don't tell to use the Discover's icon, but something more like this one for this plasmoid.

**Comment by fancytenseletters** [comment]
This is probably very subjective as it looks good in Breeze for me but I don't oppose adding new icons.

**Comment by I-Dream-in-Code** [comment]
It's an arch icon because only arch requires check updates and manual upgrade.

Gnome arch update notifier uses a similar arch logo icon

**Comment by I-Dream-in-Code** [comment]
@NerosTie  custom icon support has been added
