### ISSUE TITLE
Settings improvements

### ISSUE THREAD

**Issue by naraesk** [I-Dream-in-Code/kde-arch-update-plasmoid#23]
Two things I noticed while implementing yakuake support:

1) If aur support is enabled, pacman -Syu --noconfirm is used. If aur support is disabled, --noconfirm is not used. Is this intended?

2) Currently, you can enable "show in konsole" and "show in yakuake" at the same time, which does not make sense. You should use radio buttons, so only one option can be selected

**Comment by I-Dream-in-Code** [comment]
@naraesk 

For 1: if it shows in konsole without aur support it defaults to not enabling nocofirm so you can inspect the update process and have it be interactive. if you want noconfirm in aur you have to choose it in settings.

2: I can make it a radio button


HOWEVER the yakuake code you gave me is super buggy.

if yakuake isn't started the whole shell freezes and it fails to start a session after it resumes.  only starting it on your own fixes that issue.

Second when you run it with yakuake it fails to wait for sudo password and just quits to the `echo update finished`

Is this something on my end?

i got a notification that RunCommand is used and I need to recompile yakuake

**Comment by I-Dream-in-Code** [comment]
a13709a77e60e6d537aa28ac877faa91106accd9 fixes settings and makes it better than radio.

If it was radio I'd need 3 boxes, one for default one for konsole one for yakuake.  

Now you can select none or only 1.  

Changes are pushed to yakuake branch and will be merged once you fix yakuake

**Comment by naraesk** [comment]
> For 1: if you want noconfirm in aur you have to choose it in settings.

When aur is enabled, two commands are executed. one for updating aur, one for updating pacman. The second command always has --noconfirm, regardless of what is selected in settings.

**Comment by naraesk** [comment]
> a13709a fixes settings and makes it better than radio.
> If it was radio I'd need 3 boxes, one for default one for konsole one for yakuake.

What is so bad about having a third option? It breaks design guidelines to use checkboxes like this.

https://community.kde.org/KDE_Visual_Design_Group/HIG/CheckBox
https://community.kde.org/KDE_Visual_Design_Group/HIG/RadioButtons

Checkboxes are for selecting multiple options
Radio buttons are for selecting only one option

**Comment by I-Dream-in-Code** [comment]
It's too cluttered with three options and it says in the second bullet for radio button if it's the negation then use a checkbox.

I'll fix the pacman settings

**Comment by naraesk** [comment]
If it would be the negation, you wouldn't need three radio buttons. ;-)
