### ISSUE TITLE
Custom icon support?

### ISSUE THREAD

**Issue by drewofdoom** [I-Dream-in-Code/kde-arch-update-plasmoid#27]
I use this on Manjaro and would love to be able to add a custom icon.

**Comment by I-Dream-in-Code** [comment]
I don't think that's something I can do on my end

If you want to change it download the source and edit `package/contents/ui/archLogo.png` to the image you want

Keeping it the same name is easiest or else you need to edit every file that has it in it

**Comment by I-Dream-in-Code** [comment]
If you want it to be real robust custom image feel free to contribute a patch :)

**Comment by I-Dream-in-Code** [comment]
@drewofdoom my latest commit adds custom icon support
