### ISSUE TITLE
Add support for more AUR helpers

### ISSUE THREAD

**Issue by guicale** [I-Dream-in-Code/kde-arch-update-plasmoid#29]
I seems quite a few AUR helpers have been added to the [wiki page](https://wiki.archlinux.org/index.php/AUR_helpers), so it would be nice to add support for them.

**Comment by I-Dream-in-Code** [comment]
Ha it seems all the other ones got discontinued...

I'll get to it hopefully in the next few days but if not it'll be a few weeks as I'm moving and won't have my desktop computer

**Comment by I-Dream-in-Code** [comment]
I just updated master and the aur package

let me know if I mistyped the commands
