### ISSUE TITLE
Option "show upgrade on konsole" not saved between sessions

### ISSUE THREAD

**Issue by Tichy** [I-Dream-in-Code/kde-arch-update-plasmoid#3]
I like to view on console what's happening, to see if there are error messages or notices. When I check "show upgrade on konsole" it stays enabled only for the current session. Every time I login again, I found it unchecked.

**Comment by I-Dream-in-Code** [comment]
Thanks for reporting the bug.

When you say "session" do you mean a log out and logging back in? Restart? Both?

**Comment by I-Dream-in-Code** [comment]
fixed 

either clone this or use aur package plasma5-applets-kde-arch-update-notifier-git

I'm adding AUR support so it's better if you do the AUR package to get all the updates

**Comment by Tichy** [comment]
Thanks, but now I can't install it because perl-www-aur, which is required by checkupdates-aur, which is required by plasma5-applets-kde-arch-update-notifier-git doesn't compile (even after installing the unmentioned build dependecy perl-module-install).
This aur support requires a lot of dependencies...

**Comment by I-Dream-in-Code** [comment]
My bad I need to roll back the pkgbuild that feature isn't done

**Comment by I-Dream-in-Code** [comment]
fixed

**Comment by I-Dream-in-Code** [comment]
On the note why it's not compiling:

`perl-www-aur` has a bug in it's check command on install

Someone posted about it in aur website

Once this feature is complete if it's not fixed remove the check function from pkgbuild

**Comment by Tichy** [comment]
In data sabato 14 ottobre 2017 18:25:07 CEST, Michael Harris ha scritto:
> On the note why it's not compiling:
> 
> `perl-www-aur` has a bug in it's check command on install
> 
> Someone posted about it in aur website

Yes. It was me a minute ago ;)

Thanks for the fix. I'm trying it now. :)

**Comment by I-Dream-in-Code** [comment]
If it doesn't get fixed soon I'll make it an optional dependency

**Comment by I-Dream-in-Code** [comment]
Lol I thought is was you haha :)

Thanks for posting I was just about to

**Comment by I-Dream-in-Code** [comment]
Can you confirm it's working?

**Comment by Tichy** [comment]
In data sabato 14 ottobre 2017 18:35:09 CEST, Michael Harris ha scritto:
> Can you confirm it's working?

Yes. Now it keeps it. Thanks.

**Comment by I-Dream-in-Code** [comment]
Cool

Glad it worked out.

Simple bug I learned from aur feature

Konsole wasn't in the xml settings file so it kept deleting after each session

Put it in and it fixed it

**Comment by I-Dream-in-Code** [comment]
I decided to write my own check updates aur

It honestly should just be `pacman -Qm` then a perl search for `https://aur.archlinux.org/packages/*package name*` and get current version
