### ISSUE TITLE
Don't show packages listed in IgnorePkg in pacman.conf

### ISSUE THREAD

**Issue by ghost** [I-Dream-in-Code/kde-arch-update-plasmoid#31]
Currently after update check plasmoid shows packages which are listed in `IgnorePkg` in `pacman.conf` thus they will never be updated. It would be nice if plasmoid can ignore them too.

**Comment by Rosanna4** [comment]
> What i could do is look at the ignore packages and remove them from the list?

Yeah, that's what I thought. 

> I won't have my computer until 6/9 so I'll look at it then

Great. Thank you.

**Comment by I-Dream-in-Code** [comment]
Paste me your entire pacman.conf

Also the path of it

**Comment by Rosanna4** [comment]
Well it's quite default from `/etc/pacman.conf` [pacman.conf.txt](https://github.com/I-Dream-in-Code/kde-arch-update-plasmoid/files/2084186/pacman.conf.txt)
