### ISSUE TITLE
Cannot change icon

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [I-Dream-in-Code/kde-arch-update-plasmoid#32]
I want to change icon through (custom image) option found in the settings but after choosing icon and restart plasma the icon applet disappears

**Comment by I-Dream-in-Code** [comment]
Can you send me a copy of the icon file?

**Comment by ahmed-h-ayyad** [comment]
![path4](https://user-images.githubusercontent.com/37955014/43012229-61e8981c-8c35-11e8-8baa-2159b4e709ed.png)
I've tried several icon files, this one of them

**Comment by I-Dream-in-Code** [comment]
It's working fine on my machine.

when you restart the shell it takes a second to load the icon

**Comment by I-Dream-in-Code** [comment]
killall plasmashell

kstart5 plasmashell

**Comment by I-Dream-in-Code** [comment]
Also if no updates are available it autohides
