### ISSUE TITLE
Konsole and Yakuake not showing upgrade process

### ISSUE THREAD

**Issue by bssb** [I-Dream-in-Code/kde-arch-update-plasmoid#36]
When AUR support is disabled, Konsole does not open a window when Update System is clicked. Yakuake opens a new empty tab, with no commands. I'll be happy to submit a PR once I get it together.

**Comment by I-Dream-in-Code** [comment]
Thanks for bringing this to my attention

I should be a simple issue with commands stringlist

I'll check it out

**Comment by I-Dream-in-Code** [comment]
aa291a3fa06ce53ffbc6a21782cc4953a4a54d86 fixes issue

master and AUR package are updated
