### ISSUE TITLE
use svg icons

### ISSUE THREAD

**Issue by bssb** [I-Dream-in-Code/kde-arch-update-plasmoid#38]
The png logos look pixelated when scaled down. Like this:
![plasmoid](https://user-images.githubusercontent.com/7004951/47277662-3ec67300-d590-11e8-951b-b8087ce4d3cc.png)

Using scalable icons would look smoother. Would you accept a PR for svg icon support?

**Comment by I-Dream-in-Code** [comment]
Sure a pull request would be great

Please get svg for default, light and dark themes

**Comment by I-Dream-in-Code** [comment]
Sure

Please do svg for default, light and dark themes

**Comment by jurplel** [comment]
On it - #39

**Comment by jurplel** [comment]
This can be closed now
