### ISSUE TITLE
Dark text on dark background 

### ISSUE THREAD

**Issue by archderwelt** [I-Dream-in-Code/kde-arch-update-plasmoid#4]
Text is hardly readable with the breeze-dark theme.     
Thanks.
![screenshot_20171015_190905](https://user-images.githubusercontent.com/20864876/31587177-390247f0-b1dd-11e7-8f8c-3c44fc656224.png)

**Comment by I-Dream-in-Code** [comment]
It should be a simple fix of text color

I'll get to it in the next couple days

**Comment by I-Dream-in-Code** [comment]
simple fix it was supposed to be `theme.textColor` but it was a typo of `theme.textcolor`

feel free to use the `AUR pacakge` `plasma5-applets-kde-arch-update-notifier-git` to update 

AUR support coming soon
