### ISSUE TITLE
Autohide icon in systemtray

### ISSUE THREAD

**Issue by ghost** [I-Dream-in-Code/kde-arch-update-plasmoid#5]
Is it possible to have icon hidden in systemtray when no updates available? Currently icon is always shown when I choose "Auto" setting.

**Comment by I-Dream-in-Code** [comment]
I can look into it.

Right now I'm finally finishing aur support

**Comment by Faenriis** [comment]
This is a snippet from Discover's update notifier plasmoid.

  Plasmoid.status: {
          switch (DiscoverNotifier.state) {
              case DiscoverNotifier.NoUpdates:
              return PlasmaCore.Types.PassiveStatus;
              case DiscoverNotifier.NormalUpdates:
              case DiscoverNotifier.SecurityUpdates:
              return PlasmaCore.Types.ActiveStatus;
           }

I think it can be easily adopted here for the same purpose.

**Comment by I-Dream-in-Code** [comment]
I tried implementing it and it didn't work.

I also tried adding `visible: main.updatesPending > 0` which didn't work either

**Comment by I-Dream-in-Code** [comment]
Feel free to fork it and I'll merge a patch in

**Comment by I-Dream-in-Code** [comment]
@naraesk when i click panel settings it just gives me auto-hide but no automatic

can you walk me through how to enable it?

**Comment by I-Dream-in-Code** [comment]
@naraesk is it a specific package I'm missing?

**Comment by naraesk** [comment]
I assume you are in the wrong settings window. system panel has its own settings. Right click on the system tray (not an application icon, but e.g. on the small arrow) and open settings. There you can set the visibility of each icon in system tray.

**Comment by I-Dream-in-Code** [comment]
Oh I get it now.

I had it as it's own widget versus in the system tray
