### ISSUE TITLE
Since last update plasmoid shows previous update status

### ISSUE THREAD

**Issue by fancytenseletters** [I-Dream-in-Code/kde-arch-update-plasmoid#6]
First update checking works ok.
Second update show status from first update.
Third update shows status from second update and so on...

**Comment by I-Dream-in-Code** [comment]
When you say status is it the actual old checkupdates return value?

Or an actual status message?

**Comment by I-Dream-in-Code** [comment]
Also how are you running check updates?

Do you repeatedly click check updates?

Do you repeatedly click after an upgrade?

Hoping for more information.

I added a blocking queue to the slot but I need more background from you

**Comment by I-Dream-in-Code** [comment]
pretty sure the blocking queue fixed it as it fixed this bug I had with a different branch

**Comment by I-Dream-in-Code** [comment]
updated the master branch, let me know if that fixed it

also updated the AUR package

**Comment by fancytenseletters** [comment]
I set update timer to 60min and plasmoid always showed me packages which I already updated one hour ago instead of current updates. I had to click to check updates again to see current updates. I upgraded plasmoid and will report if this is fixed.

**Comment by fancytenseletters** [comment]
This issue seems to be fixed however plasma ui starts freezing again during update process. I hope it can be solved without issues like this in the future.

**Comment by I-Dream-in-Code** [comment]
Yeah that's the nasty thing about blocking queue

I'm gonna rewrite it with an actual mutex true multithreading

**Comment by I-Dream-in-Code** [comment]
@fancytenseletters QML makes asynchronous calls but I added a half semaphore and it shouldn't freeze and also updates correctly

I have to wait for upgrades to test further

**Comment by I-Dream-in-Code** [comment]
@fancytenseletters I fixed it and do apologize  for that bad implentation before.

the master branch and AUR package are both updates

**Comment by fancytenseletters** [comment]
@I-Dream-in-Code Hmm this time plasmoid doesn't show upgradable packages in its window. Only number of updates are shown in tray. Choosing "Update system" works ok (I'm using Konsole output).

**Comment by I-Dream-in-Code** [comment]
@fancytenseletters  somehow the` "text" : packagelist[i]` was missing `text:` and just `packageList[i]`

Updated master and AUR

**Comment by fancytenseletters** [comment]
Thanks!
