### ISSUE TITLE
error while building package from AUR

### ISSUE THREAD

**Issue by nomis6432** [I-Dream-in-Code/kde-arch-update-plasmoid#7]
I tried updating the package from the AUR with pacaur but I get an illegal instruction error. I don't know if this is something on my end but here is the konsole output: https://pastebin.com/aEpdGebC

I installed it form the AUR a few days ago without a problem so I think the issue is new.

**Comment by fancytenseletters** [comment]
Can't reproduce.

**Comment by I-Dream-in-Code** [comment]
That's not on my end

That's pacaur and been well commented on
