### ISSUE TITLE
AUR support incompatible with zsh shell

### ISSUE THREAD

**Issue by fancytenseletters** [I-Dream-in-Code/kde-arch-update-plasmoid#8]
Clicking on **Update System** inside plasmoid when an AUR update is available invokes two commands:

`/usr/bin/konsole --hold -e  pacaur -Syyu`
`/usr/bin/zsh pacaur -Syyu`

The second one fails with `/usr/bin/zsh: can't open input file: pacaur`. I tried invoking `/usr/bin/zsh pacaur -Syyu` manually and it fails with same error however when I try `/usr/bin/bash pacaur -Syyu` it succeeds.

I don't know why `/usr/bin/zsh pacaur -Syyu` is needed at all as `/usr/bin/konsole --hold -e  pacaur -Syyu` should be sufficient.

BTW: I think `-Syyu` is too radical and `-Syu` would be better choice.

**Comment by I-Dream-in-Code** [comment]
Give me the exact steps to reproduce and I'll look into it

**Comment by fancytenseletters** [comment]
1. Install zsh
2. Set /usr/bin/zsh as user shell 
3. Check AUR support in plasmoid
4. Try updating system

**Comment by I-Dream-in-Code** [comment]
I feel like I just need to set it to start the update process with /bin/bash and put konsole as an argument

**Comment by I-Dream-in-Code** [comment]
I added the argument and changed the shell and it works now.

I haven't updated the AUR package but I updated master.

If you could manually install from master and verify it's working on your end I will update the AUR package

**Comment by I-Dream-in-Code** [comment]
turns out there was an empty string as an argument and that's why it was throwing an error

updated so please verify by cloning master and running the install script

**Comment by fancytenseletters** [comment]
It's working now, thanks. :smile:
